### ISSUE TITLE
Change logic to create non-random consecutive and shorter temporary directories

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/angela#15]
Temporary directory is created by using a UUID, which:
- is long
- is not consecutive (because random)

It would be nice is temp dirs would be created with shorter name with a timestamp, so that when running tests locally this is really fast to find the right folders. Newly running test would be at the end.

Tmp dirs could be created with such way:
```java
root = Files.createTempDirectory(parent, System.currentTimeMillis() + "-");
```

This created something like:

![image](https://user-images.githubusercontent.com/61346/74772133-6c432f80-525d-11ea-81e7-714127b950b7.png)

And more recently run test will be at the end.

Compared to now:

![image](https://user-images.githubusercontent.com/61346/74772171-7fee9600-525d-11ea-9114-0fe1ab0fbaeb.png)

Also, this would help a lot on windows...

**Comment by aurbroszniowski** [comment]
Are you sure this is related to Angela? There is no creation of UUID-based temp directory  in Angela AFAIK

**Comment by mathieucarbou** [comment]
@saurabhagas could confirm or not.
he told me to copy all these issues in itrac also.

Is it the random UUID we see here ?

`new ClusterFactory(UUID.randomUUID().toString(), createConfigContext(clusterDef.stripes(), clusterDef.nodesPerStripe()));`

**Comment by aurbroszniowski** [comment]
Ok then that makes sense, the temporary work directory in Angela is made of the test name (passed to the ClusterFactory) and the execution time (in order to locate the folder easily according to the time of the test execution like you want to). 

e.g.
new ClusterFactory("InstallTest::testSsh"...
   running at 2:10:00 will produce:
InstallTest__testSsh-021000

it looks like the test code needs to be changed, probably to use JUnit to dynamically retrieve the test and method name instead of generating a UUID
